import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Importation de la police Poppins
import "./globals.css";

const poppinsFont = Poppins({ // Renommé pour éviter la collision
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Fadj-ma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "./globals.css";

// const Poppins = Poppins({
//   variable: "Poppins",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${Poppins.variable} ${Poppins.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
